export const projects = [
  {
    slug: "diaspocare",
    title: "DiaspoCare",
    description: "Connecting diaspora families with healthcare providers back home.",
    year: "2026",
    image: "https://www.diaspocare.com/og.jpg",
    url: "https://diaspocare.com",
    tags: ["Healthcare", "Web Platform"],
  },
  {
    slug: "vinisee-movers",
    title: "Vinisee Movers",
    description: "Eldoret's most trusted professional moving company — residential & office relocation.",
    year: "2026",
    image: "https://vinisee-movers.co.ke/og-image.png",
    url: "https://vinisee-movers.co.ke",
    tags: ["Logistics", "Local Business"],
  },
  {
    slug: "rable-bakes",
    title: "Rable Bakes",
    description: "Luxury custom cakes for weddings, birthdays, and celebrations in Juja, Kasarani & Nairobi.",
    year: "2026",
    image: "https://d8j0ntlcm91z4.cloudfront.net/user_3GMM1ZXfFqeRT7y5z9MLauQ1U80/hf_20260712_094603_d066f509-71d0-4d74-b3f6-1a5d38d2cae3.png",
    url: "https://rablebakes.co.ke",
    tags: ["Bakery", "E-commerce"],
  },
  {
    slug: "bmw-galore",
    title: "BMW Galore",
    description: "Kenya's #1 BMW marketplace — buy and sell verified premium BMW listings.",
    year: "2026",
    image: "https://bmwgalore.co.ke/og-image.jpg",
    url: "https://bmwgalore.co.ke",
    tags: ["Marketplace", "Automotive"],
  },
];
